# Generated by Django 5.1.2 on 2024-11-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_timetraveller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='title',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='title',
        ),
    ]
